import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
];

const translations: Record<string, Record<string, string>> = {
  en: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "Your savings, visualized",
    "nav.home": "Home",
    "nav.stats": "Stats",
    "nav.settings": "Settings",
    "streak.day": "day streak",
    "goals.title": "Goals",
    "goals.history": "History",
    "goals.empty.title": "No goals yet",
    "goals.empty.subtitle": "Tap \"New Goal\" to start saving!",
    "goals.new": "New Goal",
    "goals.reached": "🎉 Goal reached!",
    "goals.daily": "Daily",
    "goals.weekly": "Weekly",
    "goals.monthly": "Monthly",
    "goals.of": "of",
    "goals.total": "total goals",
    "goals.add": "Add",
    "dialog.create.title": "Create Savings Goal",
    "dialog.create.name": "Goal Name",
    "dialog.create.name.placeholder": "e.g. New iPhone",
    "dialog.create.target": "Target Amount",
    "dialog.create.date": "Target Date",
    "dialog.create.icon": "Icon",
    "dialog.create.submit": "Create Goal",
    "dialog.add.title": "Add to",
    "dialog.add.amount": "Amount",
    "dialog.add.note": "Note (optional)",
    "dialog.add.note.placeholder": "Birthday money...",
    "dialog.add.submit": "Save",
    "history.title": "Recent Activity",
    "history.empty": "No savings yet. Start adding to your goals!",
    "history.deleted": "Deleted goal",
    "stats.title": "Statistics",
    "stats.total": "Total Saved",
    "stats.month": "This Month",
    "stats.chart": "Last 7 Days",
    "stats.saved": "Saved",
    "settings.title": "Settings",
    "settings.theme": "Theme",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.theme.system": "System",
    "settings.currency": "Currency",
    "settings.currency.select": "Select Currency",
    "settings.currency.search": "Search currencies...",
    "settings.language": "Language",
    "settings.language.select": "Select Language",
    "settings.notifications": "Notifications",
    "settings.notifications.off": "Off",
    "settings.export": "Export Data",
    "settings.reset": "Reset All Data",
    "settings.reset.confirm": "Are you sure you want to delete all data? This cannot be undone.",
    "settings.version": "SaveJar v1.0",
  },
  fr: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "Vos économies, visualisées",
    "nav.home": "Accueil",
    "nav.stats": "Stats",
    "nav.settings": "Réglages",
    "streak.day": "jours de suite",
    "goals.title": "Objectifs",
    "goals.history": "Historique",
    "goals.empty.title": "Pas encore d'objectifs",
    "goals.empty.subtitle": "Appuyez sur \"Nouvel objectif\" pour commencer !",
    "goals.new": "Nouvel objectif",
    "goals.reached": "🎉 Objectif atteint !",
    "goals.daily": "Jour",
    "goals.weekly": "Semaine",
    "goals.monthly": "Mois",
    "goals.of": "sur",
    "goals.total": "objectifs totaux",
    "goals.add": "Ajouter",
    "dialog.create.title": "Créer un objectif d'épargne",
    "dialog.create.name": "Nom de l'objectif",
    "dialog.create.name.placeholder": "ex. Nouvel iPhone",
    "dialog.create.target": "Montant cible",
    "dialog.create.date": "Date cible",
    "dialog.create.icon": "Icône",
    "dialog.create.submit": "Créer l'objectif",
    "dialog.add.title": "Ajouter à",
    "dialog.add.amount": "Montant",
    "dialog.add.note": "Note (optionnel)",
    "dialog.add.note.placeholder": "Argent d'anniversaire...",
    "dialog.add.submit": "Enregistrer",
    "history.title": "Activité récente",
    "history.empty": "Pas encore d'épargne. Commencez à ajouter à vos objectifs !",
    "history.deleted": "Objectif supprimé",
    "stats.title": "Statistiques",
    "stats.total": "Total épargné",
    "stats.month": "Ce mois",
    "stats.chart": "7 derniers jours",
    "stats.saved": "Épargné",
    "settings.title": "Réglages",
    "settings.theme": "Thème",
    "settings.theme.light": "Clair",
    "settings.theme.dark": "Sombre",
    "settings.theme.system": "Système",
    "settings.currency": "Devise",
    "settings.currency.select": "Choisir la devise",
    "settings.currency.search": "Rechercher des devises...",
    "settings.language": "Langue",
    "settings.language.select": "Choisir la langue",
    "settings.notifications": "Notifications",
    "settings.notifications.off": "Désactivé",
    "settings.export": "Exporter les données",
    "settings.reset": "Réinitialiser toutes les données",
    "settings.reset.confirm": "Êtes-vous sûr de vouloir supprimer toutes les données ? Cette action est irréversible.",
    "settings.version": "SaveJar v1.0",
  },
  it: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "I tuoi risparmi, visualizzati",
    "nav.home": "Home",
    "nav.stats": "Statistiche",
    "nav.settings": "Impostazioni",
    "streak.day": "giorni di fila",
    "goals.title": "Obiettivi",
    "goals.history": "Cronologia",
    "goals.empty.title": "Nessun obiettivo ancora",
    "goals.empty.subtitle": "Tocca \"Nuovo obiettivo\" per iniziare!",
    "goals.new": "Nuovo obiettivo",
    "goals.reached": "🎉 Obiettivo raggiunto!",
    "goals.daily": "Giorno",
    "goals.weekly": "Settimana",
    "goals.monthly": "Mese",
    "goals.of": "di",
    "goals.total": "obiettivi totali",
    "goals.add": "Aggiungi",
    "dialog.create.title": "Crea obiettivo di risparmio",
    "dialog.create.name": "Nome obiettivo",
    "dialog.create.name.placeholder": "es. Nuovo iPhone",
    "dialog.create.target": "Importo obiettivo",
    "dialog.create.date": "Data obiettivo",
    "dialog.create.icon": "Icona",
    "dialog.create.submit": "Crea obiettivo",
    "dialog.add.title": "Aggiungi a",
    "dialog.add.amount": "Importo",
    "dialog.add.note": "Nota (opzionale)",
    "dialog.add.note.placeholder": "Soldi di compleanno...",
    "dialog.add.submit": "Salva",
    "history.title": "Attività recente",
    "history.empty": "Nessun risparmio ancora. Inizia ad aggiungere ai tuoi obiettivi!",
    "history.deleted": "Obiettivo eliminato",
    "stats.title": "Statistiche",
    "stats.total": "Totale risparmiato",
    "stats.month": "Questo mese",
    "stats.chart": "Ultimi 7 giorni",
    "stats.saved": "Risparmiato",
    "settings.title": "Impostazioni",
    "settings.theme": "Tema",
    "settings.theme.light": "Chiaro",
    "settings.theme.dark": "Scuro",
    "settings.theme.system": "Sistema",
    "settings.currency": "Valuta",
    "settings.currency.select": "Seleziona valuta",
    "settings.currency.search": "Cerca valute...",
    "settings.language": "Lingua",
    "settings.language.select": "Seleziona lingua",
    "settings.notifications": "Notifiche",
    "settings.notifications.off": "Disattivato",
    "settings.export": "Esporta dati",
    "settings.reset": "Ripristina tutti i dati",
    "settings.reset.confirm": "Sei sicuro di voler eliminare tutti i dati? Questa azione è irreversibile.",
    "settings.version": "SaveJar v1.0",
  },
  de: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "Deine Ersparnisse, visualisiert",
    "nav.home": "Start",
    "nav.stats": "Statistik",
    "nav.settings": "Einstellungen",
    "streak.day": "Tage Serie",
    "goals.title": "Ziele",
    "goals.history": "Verlauf",
    "goals.empty.title": "Noch keine Ziele",
    "goals.empty.subtitle": "Tippe auf \"Neues Ziel\" um zu starten!",
    "goals.new": "Neues Ziel",
    "goals.reached": "🎉 Ziel erreicht!",
    "goals.daily": "Täglich",
    "goals.weekly": "Wöchentlich",
    "goals.monthly": "Monatlich",
    "goals.of": "von",
    "goals.total": "Gesamtziele",
    "goals.add": "Hinzufügen",
    "dialog.create.title": "Sparziel erstellen",
    "dialog.create.name": "Zielname",
    "dialog.create.name.placeholder": "z.B. Neues iPhone",
    "dialog.create.target": "Zielbetrag",
    "dialog.create.date": "Zieldatum",
    "dialog.create.icon": "Symbol",
    "dialog.create.submit": "Ziel erstellen",
    "dialog.add.title": "Hinzufügen zu",
    "dialog.add.amount": "Betrag",
    "dialog.add.note": "Notiz (optional)",
    "dialog.add.note.placeholder": "Geburtstagsgeld...",
    "dialog.add.submit": "Speichern",
    "history.title": "Letzte Aktivität",
    "history.empty": "Noch keine Ersparnisse. Fang an, zu deinen Zielen hinzuzufügen!",
    "history.deleted": "Gelöschtes Ziel",
    "stats.title": "Statistiken",
    "stats.total": "Gesamt gespart",
    "stats.month": "Diesen Monat",
    "stats.chart": "Letzte 7 Tage",
    "stats.saved": "Gespart",
    "settings.title": "Einstellungen",
    "settings.theme": "Design",
    "settings.theme.light": "Hell",
    "settings.theme.dark": "Dunkel",
    "settings.theme.system": "System",
    "settings.currency": "Währung",
    "settings.currency.select": "Währung wählen",
    "settings.currency.search": "Währungen suchen...",
    "settings.language": "Sprache",
    "settings.language.select": "Sprache wählen",
    "settings.notifications": "Benachrichtigungen",
    "settings.notifications.off": "Aus",
    "settings.export": "Daten exportieren",
    "settings.reset": "Alle Daten zurücksetzen",
    "settings.reset.confirm": "Bist du sicher, dass du alle Daten löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
    "settings.version": "SaveJar v1.0",
  },
  es: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "Tus ahorros, visualizados",
    "nav.home": "Inicio",
    "nav.stats": "Estadísticas",
    "nav.settings": "Ajustes",
    "streak.day": "días seguidos",
    "goals.title": "Metas",
    "goals.history": "Historial",
    "goals.empty.title": "Sin metas aún",
    "goals.empty.subtitle": "¡Toca \"Nueva meta\" para empezar!",
    "goals.new": "Nueva meta",
    "goals.reached": "🎉 ¡Meta alcanzada!",
    "goals.daily": "Diario",
    "goals.weekly": "Semanal",
    "goals.monthly": "Mensual",
    "goals.of": "de",
    "goals.total": "metas totales",
    "goals.add": "Agregar",
    "dialog.create.title": "Crear meta de ahorro",
    "dialog.create.name": "Nombre de la meta",
    "dialog.create.name.placeholder": "ej. Nuevo iPhone",
    "dialog.create.target": "Monto objetivo",
    "dialog.create.date": "Fecha objetivo",
    "dialog.create.icon": "Ícono",
    "dialog.create.submit": "Crear meta",
    "dialog.add.title": "Agregar a",
    "dialog.add.amount": "Monto",
    "dialog.add.note": "Nota (opcional)",
    "dialog.add.note.placeholder": "Dinero de cumpleaños...",
    "dialog.add.submit": "Guardar",
    "history.title": "Actividad reciente",
    "history.empty": "Sin ahorros aún. ¡Empieza a agregar a tus metas!",
    "history.deleted": "Meta eliminada",
    "stats.title": "Estadísticas",
    "stats.total": "Total ahorrado",
    "stats.month": "Este mes",
    "stats.chart": "Últimos 7 días",
    "stats.saved": "Ahorrado",
    "settings.title": "Ajustes",
    "settings.theme": "Tema",
    "settings.theme.light": "Claro",
    "settings.theme.dark": "Oscuro",
    "settings.theme.system": "Sistema",
    "settings.currency": "Moneda",
    "settings.currency.select": "Seleccionar moneda",
    "settings.currency.search": "Buscar monedas...",
    "settings.language": "Idioma",
    "settings.language.select": "Seleccionar idioma",
    "settings.notifications": "Notificaciones",
    "settings.notifications.off": "Desactivado",
    "settings.export": "Exportar datos",
    "settings.reset": "Restablecer todos los datos",
    "settings.reset.confirm": "¿Estás seguro de que deseas eliminar todos los datos? Esta acción no se puede deshacer.",
    "settings.version": "SaveJar v1.0",
  },
  ja: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "あなたの貯蓄を視覚化",
    "nav.home": "ホーム",
    "nav.stats": "統計",
    "nav.settings": "設定",
    "streak.day": "日連続",
    "goals.title": "目標",
    "goals.history": "履歴",
    "goals.empty.title": "まだ目標がありません",
    "goals.empty.subtitle": "「新しい目標」をタップして始めましょう！",
    "goals.new": "新しい目標",
    "goals.reached": "🎉 目標達成！",
    "goals.daily": "日",
    "goals.weekly": "週",
    "goals.monthly": "月",
    "goals.of": "/",
    "goals.total": "合計目標",
    "goals.add": "追加",
    "dialog.create.title": "貯蓄目標を作成",
    "dialog.create.name": "目標名",
    "dialog.create.name.placeholder": "例：新しいiPhone",
    "dialog.create.target": "目標金額",
    "dialog.create.date": "目標日",
    "dialog.create.icon": "アイコン",
    "dialog.create.submit": "目標を作成",
    "dialog.add.title": "追加先",
    "dialog.add.amount": "金額",
    "dialog.add.note": "メモ（任意）",
    "dialog.add.note.placeholder": "お誕生日のお金...",
    "dialog.add.submit": "保存",
    "history.title": "最近のアクティビティ",
    "history.empty": "まだ貯蓄がありません。目標に追加を始めましょう！",
    "history.deleted": "削除された目標",
    "stats.title": "統計",
    "stats.total": "合計貯蓄",
    "stats.month": "今月",
    "stats.chart": "過去7日間",
    "stats.saved": "貯蓄額",
    "settings.title": "設定",
    "settings.theme": "テーマ",
    "settings.theme.light": "ライト",
    "settings.theme.dark": "ダーク",
    "settings.theme.system": "システム",
    "settings.currency": "通貨",
    "settings.currency.select": "通貨を選択",
    "settings.currency.search": "通貨を検索...",
    "settings.language": "言語",
    "settings.language.select": "言語を選択",
    "settings.notifications": "通知",
    "settings.notifications.off": "オフ",
    "settings.export": "データをエクスポート",
    "settings.reset": "すべてのデータをリセット",
    "settings.reset.confirm": "すべてのデータを削除してもよろしいですか？この操作は元に戻せません。",
    "settings.version": "SaveJar v1.0",
  },
  zh: {
    "app.title": "SaveJar 🫙",
    "app.subtitle": "你的储蓄，可视化",
    "nav.home": "首页",
    "nav.stats": "统计",
    "nav.settings": "设置",
    "streak.day": "天连续",
    "goals.title": "目标",
    "goals.history": "历史",
    "goals.empty.title": "还没有目标",
    "goals.empty.subtitle": "点击"新目标"开始储蓄！",
    "goals.new": "新目标",
    "goals.reached": "🎉 目标达成！",
    "goals.daily": "每日",
    "goals.weekly": "每周",
    "goals.monthly": "每月",
    "goals.of": "/",
    "goals.total": "总目标",
    "goals.add": "添加",
    "dialog.create.title": "创建储蓄目标",
    "dialog.create.name": "目标名称",
    "dialog.create.name.placeholder": "例如：新iPhone",
    "dialog.create.target": "目标金额",
    "dialog.create.date": "目标日期",
    "dialog.create.icon": "图标",
    "dialog.create.submit": "创建目标",
    "dialog.add.title": "添加到",
    "dialog.add.amount": "金额",
    "dialog.add.note": "备注（可选）",
    "dialog.add.note.placeholder": "生日红包...",
    "dialog.add.submit": "保存",
    "history.title": "最近活动",
    "history.empty": "还没有储蓄。开始为你的目标添加吧！",
    "history.deleted": "已删除的目标",
    "stats.title": "统计数据",
    "stats.total": "总储蓄",
    "stats.month": "本月",
    "stats.chart": "最近7天",
    "stats.saved": "已储蓄",
    "settings.title": "设置",
    "settings.theme": "主题",
    "settings.theme.light": "浅色",
    "settings.theme.dark": "深色",
    "settings.theme.system": "系统",
    "settings.currency": "货币",
    "settings.currency.select": "选择货币",
    "settings.currency.search": "搜索货币...",
    "settings.language": "语言",
    "settings.language.select": "选择语言",
    "settings.notifications": "通知",
    "settings.notifications.off": "关闭",
    "settings.export": "导出数据",
    "settings.reset": "重置所有数据",
    "settings.reset.confirm": "确定要删除所有数据吗？此操作无法撤消。",
    "settings.version": "SaveJar v1.0",
  },
};

const LANG_KEY = "savings-tracker-language";

interface LanguageContextType {
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: LANGUAGES[0],
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem(LANG_KEY);
      if (saved) return JSON.parse(saved);
    } catch {}
    return LANGUAGES[0];
  });

  useEffect(() => {
    localStorage.setItem(LANG_KEY, JSON.stringify(language));
  }, [language]);

  const setLanguage = (l: Language) => setLanguageState(l);

  const t = (key: string): string => {
    return translations[language.code]?.[key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
